### ISSUE TITLE
NLog FileTarget KeepFileOpen=true

### ISSUE THREAD

**Issue by snakefoot** [Macross-Software/core#8]
NLog opens and closes the file for every file-write by default for compatibility reasons. So instead of doing this:

https://github.com/Macross-Software/core/blob/74f37d674409b3deff39e00163585d3763131051/ClassLibraries/Macross.Logging.Files/Benchmarks/NLogProvider.cs#L30-L34

Then do like this:

```c#
 Target Target = new FileTarget("File") 
 { 
 	FileName = $"{LogFileDirectoryPath}nlog -${{shortdate}}.log", 
 	Layout = Layout,
        KeepFileOpen = true,       // Serilog Default, but not for NLog
        ConcurrentWrites = false,  // Same as Serilog Shared
        Autoflush = true,          // Same as Serilog Buffered
 }; 
```

If you want to increase performance even further, then you can enable NLog AsyncWrapper (Enables batch witing of LogEvents using background-timer-thread. Gives much better performance when multiple threads are concurrently logging):

```c#
Target = new AsyncTargetWrapper("FileAsync", Target) { OverflowAction = AsyncTargetWrapperOverflowAction.Grow };
```

See also: https://github.com/NLog/NLog/wiki/performance

**Comment by snakefoot** [comment]
Limited to 4 threads (instead of 10), because my CPU is 4 core without hyperthreading:

|                      Method | NumberOfThreads |       Mean |    Error |   StdDev | Completed Work Items | Lock Contentions |      Gen 0 |     Gen 1 |     Gen 2 | Allocated |
|---------------------------- |---------------- |-----------:|---------:|---------:|---------------------:|-----------------:|-----------:|----------:|----------:|----------:|
|               NLogBenchmark |               1 |   164.4 ms |  3.44 ms | 10.15 ms |               5.0000 |                - |  5000.0000 |         - |         - |  15.72 MB |
|          NLogAsyncBenchmark |               1 |   103.7 ms |  3.54 ms | 10.43 ms |              23.0000 |                - |  4000.0000 | 1000.0000 |         - |  25.49 MB |
|            SerilogBenchmark |               1 |   238.0 ms |  4.74 ms | 11.81 ms |               2.0000 |                - | 13000.0000 |         - |         - |  40.19 MB |
| MacrossFileLoggingBenchmark |               1 |   213.0 ms |  4.24 ms |  5.81 ms |               3.0000 |                - |  4000.0000 | 2000.0000 |         - |  21.21 MB |
|               NLogBenchmark |               4 | 1,317.7 ms | 27.34 ms | 49.30 ms |               5.0000 |       57944.0000 | 20000.0000 | 1000.0000 |         - |  62.76 MB |
|          NLogAsyncBenchmark |               4 |   289.8 ms |  5.68 ms |  8.84 ms |              57.0000 |          19.0000 | 19000.0000 | 8000.0000 | 3000.0000 | 110.29 MB |
|            SerilogBenchmark |               4 |   780.6 ms | 16.34 ms | 46.88 ms |               2.0000 |        9390.0000 | 54000.0000 |         - |         - | 160.72 MB |
| MacrossFileLoggingBenchmark |               4 |   740.6 ms | 14.22 ms | 16.93 ms |               4.0000 |          13.0000 | 16000.0000 | 6000.0000 | 2000.0000 |  84.79 MB |

It is great to see that Microsoft `ConcurrentQueue` gives very little congestion for NLogAsync and Macross FileLoggerProvider. It can be dangerous to have an unbound queue, which is why NLog defaults to `Discard` (Instead of `Grow` which is used by Macross FileLoggerProvider).

But the NLogAsync wins because it is able to perform batch-writing of LogEvents, where Macross FileLoggerProvider writes one at a time, and flushes. Think Macross FileLoggerProvider would become faster if it delayed the explicit call to `stream.Flush();` for every 200 message (or when drained all messages).

Here is the updated NLogProvider with `AsyncTargetWrapper`-support:
```c#
	public static class NLogProvider
	{
		public const string LogFileDirectoryPath = "C:\\LogsPerf\\NLog\\";
		public const string LogFileAsyncDirectoryPath = "C:\\LogsPerf\\NLogAsync\\";

		public static (IHost Host, ILoggerProvider LoggerProvider) CreateNLogProvider(bool asyncWriter = false)
		{
			LoggingConfiguration Config = new LoggingConfiguration();

			JsonLayout Layout = new JsonLayout
			{
				IncludeAllProperties = true
			};

			Layout.Attributes.Add(new JsonAttribute("time", "${longdate}"));
			Layout.Attributes.Add(new JsonAttribute("threadId", "${threadid}") { Encode = false });
			Layout.Attributes.Add(new JsonAttribute("level", "${level:upperCase=true}"));
			Layout.Attributes.Add(new JsonAttribute("message", "${message}"));

			var logDirectory = asyncWriter ? LogFileAsyncDirectoryPath : LogFileDirectoryPath;

			Target Target = new FileTarget("File")
			{
				FileName = $"{logDirectory}nlog -${{shortdate}}.log",
				Layout = Layout,
				KeepFileOpen = true,       // Default for Serilog, but not for NLog
				ConcurrentWrites = false,  // Matches Serilog Shared
				AutoFlush = true,          // Matches Serilog Buffered
			};

			if (asyncWriter)
			{
				// Using unbound grow to match Macross FileLoggerProvider
				Target = new AsyncTargetWrapper("FileAsync", Target) { OverflowAction = AsyncTargetWrapperOverflowAction.Grow };
			}

			Config.AddRuleForAllLevels(Target, "*", true);

			LogManager.Configuration = Config;

			IHost host = Host
				.CreateDefaultBuilder()
				.ConfigureLogging(builder =>
				{
					builder.ClearProviders();
					builder.AddProvider(new NLogLoggerProvider(new NLogProviderOptions { ShutdownOnDispose = true }));
				}).Build();

			return (host, host.Services.GetRequiredService<ILoggerProvider>());
		}
	}
```

**Comment by snakefoot** [comment]
Tried to post a comment for your blog-post:

https://blog.macrosssoftware.com/index.php/2020/05/08/structured-logging-message-correlation/

But failed with the error "Error: You have entered an incorrect reCAPTCHA value.
 Click the BACK button on your browser and try again." but there is not visible `reCAPTCHA` (Tried using Chrome and Firefox).

**Comment by CodeBlanch** [comment]
@snakefoot Wow! Amazing feedback thank you. Curious what you were up to, comparing different loggers or something? Sorry about that blog bug. It happened to me one time too but I haven't had a chance to dig into it yet. Don't know much about WordPress plugins.

I just pushed updates to the logging stuff. I tried to tweak all the settings to get things as close to "apple-to-apples" as I could. New benchmarks are below.

When I used `AsyncTargetWrapper` with NLog the performance was insane. But digging into it a bit more, I don't think it was a fair test against what the other two providers were doing. During the benchmark NLog was basically just building batches. Then in its flush it would write them out, super fast. This was really noticeable once I turned on file rolling based on size for all 3. Serilog & Macross would write ~200 files. NLog would write ~5 files and then one really big file. So to keep things fair, I left `AsyncTargetWrapper` out. Do you know of a way to use `AsyncTargetWrapper` but still have it roll on size? I think that would be more of a fair comparison with what Macross is really doing, which is essentially queuing everything up during the benchmark and then in its flush writing them out to disk in a tight loop (respecting roll settings while it does it).

This benchmark is proving quite difficult to get correct.

I liked your idea about buffering up the messages. I actually implemented it (two different ways) and wrote a benchmark. But, surprisingly, I didn't see any real difference. If anything, it took a performance hit trying to flush out stuff that sits for a while. I think this may be due to how Windows maintains an OS buffer on top of what .NET is doing? In the end I decided to leave in the Flush after every log write. I'm not totally convinced there isn't a way to do it and pick up some benefit though.
```
BenchmarkDotNet=v0.12.0, OS=Windows 10.0.19041
Intel Core i9-9880H CPU 2.30GHz, 1 CPU, 16 logical and 8 physical cores
.NET Core SDK=3.1.301
  [Host]     : .NET Core 3.1.5 (CoreCLR 4.700.20.26901, CoreFX 4.700.20.27001), X64 RyuJIT
  Job-RPMLLG : .NET Core 3.1.5 (CoreCLR 4.700.20.26901, CoreFX 4.700.20.27001), X64 RyuJIT
```
|                      Method | NumberOfThreads |       Mean |     Error |    StdDev |     Median | Completed Work Items | Lock Contentions |      Gen 0 |     Gen 1 | Gen 2 | Allocated |
|---------------------------- |---------------- |-----------:|----------:|----------:|-----------:|---------------------:|-----------------:|-----------:|----------:|------:|----------:|
|               NLogBenchmark |               1 |   320.7 ms |   6.39 ms |  14.04 ms |   319.9 ms |              69.0000 |                - |  1000.0000 |         - |     - |  11.66 MB |
|            SerilogBenchmark |               1 |   230.4 ms |   5.63 ms |  15.41 ms |   227.5 ms |               2.0000 |                - |  2000.0000 |         - |     - |  18.81 MB |
| MacrossFileLoggingBenchmark |               1 |   175.0 ms |   3.47 ms |   6.85 ms |   175.4 ms |               2.0000 |                - |          - |         - |     - |   6.79 MB |
|               NLogBenchmark |               4 | 1,898.9 ms |  54.91 ms | 158.43 ms | 1,881.0 ms |             269.0000 |        4941.0000 | 11000.0000 | 2000.0000 |     - |   88.7 MB |
|            SerilogBenchmark |               4 | 1,607.9 ms | 168.49 ms | 496.79 ms | 1,362.0 ms |               2.0000 |        7163.0000 | 16000.0000 | 1000.0000 |     - | 128.29 MB |
| MacrossFileLoggingBenchmark |               4 |   609.7 ms |  27.32 ms |  53.93 ms |   599.7 ms |               3.0000 |           6.0000 |  3000.0000 | 1000.0000 |     - |  27.14 MB |

I definitely owe NLog an apology. It is much better once you dial in the settings to match what you are trying to accomplish.

**Comment by snakefoot** [comment]
> Curious what you were up to, comparing different loggers or something?

I just read your blog-article, and was curious why NLog was making you say: "I cannot recommend NLog or Log4Net. I refuse to even link them!"

> NLog would write ~5 files and then one really big file

Yes when making an explicit flush in NLog, then it empties its buffer in a single write-operation.

I guess this conflicts with the synthetic nature of the benchmark. But it works well in the real-world.

**Comment by snakefoot** [comment]
You don't need this setting for the NLog FileTarget:

`ArchiveEvery = FileArchivePeriod.Day,`

Because you already have the ${shortdate} in the FileName. The above setting for static-filenames.

**Comment by CodeBlanch** [comment]
I updated the blog with a link to NLog and an apology 👍

**Comment by snakefoot** [comment]
I'm okay if you just strike-through or remove the statement of not recommending NLog in the article. The apology is not needed.


Sent from my Sony Xperia


---- Mikel Blanchard wrote ----


I updated the blog with a link to NLog and an apology 👍
